---

name: Simple Python Project

on: 
  push:
    branches:
     - main 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask pytest
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest -v -s /test_app.py


  build_and_push:
    runs-on: ${{ matrix.runner}}
    strategy:
      matrix:
        runner: [ubuntu-22.04]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
         docker build -t samuel78996/my-app:${{ env.SHORT_SHA }} .
      - name: Login to Dockerhub
        run: |
         echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push to Dockerhub
        run: |
          docker push samuel78996/my-app:${{ env.SHORT_SHA }}
      - name: Configure git
        run: |
         git config --local user.email "example.com"
         git config --local user.name "example123"
      - name: Update Helm Chart with new image tag
        run: |
          sed -i "s/tag:.*/tag: $SHORT_SHA/" ./my-app/values.yaml
          git add ./my-app/values.yaml
          git commit -m "Updated image tag to $SHORT_SHA"
          git push
